### ISSUE TITLE
How to Configure License in Helm Chart

### ISSUE THREAD

**Issue by aine-b** [honestica/docker-looker#89]
Hi, in the README it says "You have to configure LICENSE and EMAIL variable to be able to build the docker image." Can you please give me more information about how to configure the license and email variables in my helm chart so it can successfully pull this docker image? Currently I have:

```
imagePullSecrets:
  - name: looker-license
```

Where looker-license is a secret with:

```
Data
====
email:    24 bytes
license:  20 bytes
```

And I'm getting the following error: 

```
2m37s (x4 over 4m10s)   Warning   Failed                   Pod/looker-74dfdbcd57-kbsrr    Failed to pull image "honestica/looker:2.16.0": reading manifest 2.16.0 in docker.io/honestica/looker: requested access to the resource is denied
```

Could you please let me know what I've misconfigured? Thanks

**Comment by Hosade** [comment]
Hi,
The `honestica/looker` is private as the binary needs license to be downloaded.

The way we do it is : 
- download the .jar file through `make download` with license informations
- build and push image on repo
- use this repo to pull image from the chart

**Comment by aine-b** [comment]
Hi,

Thank you so much for your reply. So to clarify, the steps are to:

1. Download the JARs (looker.jar and looker-dependencies.jar) using the license information.
2. Build the image using the Dockerfile in this repo (https://github.com/honestica/docker-looker/blob/master/Dockerfile) ensuring that the downloaded JAR files are available to be copied across.
3. Point to this image when deploying the helm chart.

Is that all correct?

**Comment by Hosade** [comment]
Yes, it's correct
